# Generated by Django 3.2.7 on 2021-09-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0004_auto_20210911_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardAPI.tipoequipos')),
            ],
        ),
    ]
