# Generated by Django 3.2.7 on 2021-09-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0005_equipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEquipoReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardAPI.equipos')),
                ('file_path', models.CharField(max_length=512)),
            ],
        ),
    ]
