# Generated by Django 3.2.7 on 2021-09-24 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0005_equipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camposlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoequipos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LogEquipoReg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=512)),
                ('fecha_registro', models.DateTimeField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardAPI.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='LogEquipoData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardAPI.camposlog')),
                ('log_equipo_reg', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardAPI.logequipodata')),
            ],
        ),
    ]
