# Generated by Django 3.2.7 on 2021-09-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0006_auto_20210924_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logequipodata',
            name='log_equipo_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboardAPI.logequiporeg'),
        ),
    ]
