# Generated by Django 3.2.7 on 2021-09-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0007_logequipodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camposlog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logequipodata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logequiporeg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoequipos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
