# Generated by Django 3.2.7 on 2021-09-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0008_auto_20210914_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='logequiporeg',
            name='file_path',
            field=models.CharField(default=' ', max_length=512),
            preserve_default=False,
        ),
    ]
