# Generated by Django 3.2.7 on 2021-09-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0009_logequiporeg_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='logequiporeg',
            name='log_equipo_data',
            field=models.ManyToManyField(to='dashboardAPI.LogEquipoData'),
        ),
    ]
