# Generated by Django 3.2.7 on 2021-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0010_logequiporeg_log_equipo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logequiporeg',
            name='log_equipo_data',
            field=models.ManyToManyField(related_name='id_log_reg', to='dashboardAPI.LogEquipoData'),
        ),
    ]
