# Generated by Django 3.2.7 on 2021-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0011_alter_logequiporeg_log_equipo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logequipodata',
            name='id_log_reg',
        ),
        migrations.AddField(
            model_name='logequipodata',
            name='log_equipo_reg',
            field=models.ManyToManyField(to='dashboardAPI.LogEquipoData'),
        ),
        migrations.AlterField(
            model_name='logequiporeg',
            name='log_equipo_data',
            field=models.ManyToManyField(to='dashboardAPI.LogEquipoData'),
        ),
    ]
