# Generated by Django 3.2.7 on 2021-09-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0012_auto_20210922_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logequipodata',
            name='log_equipo_reg',
        ),
    ]
