# Generated by Django 3.2.7 on 2021-09-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0013_remove_logequipodata_log_equipo_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logequipodata',
            old_name='key_id',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='logequiporeg',
            old_name='id_equipo',
            new_name='equipo',
        ),
    ]
