# Generated by Django 3.2.7 on 2021-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardAPI', '0014_auto_20210922_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logequiporeg',
            name='log_equipo_data',
        ),
        migrations.AddField(
            model_name='logequipodata',
            name='log_equipo_reg',
            field=models.ManyToManyField(to='dashboardAPI.LogEquipoReg'),
        ),
    ]
